import { describe, expect, it } from "vitest";
import cases from "./feature-parity-cases.json";
import { normalizeLandmarks } from "../landmark-normalizer";
import { extractFeaturesForTest } from "../gesture-engine";

/**
 * Cross-language parity between the browser engine and the training pipeline.
 *
 * The model is trained in Python and served to TypeScript, so any divergence in
 * feature construction feeds it input from a distribution it never saw. That is
 * not a crash — it is a model that quietly returns wrong labels at low
 * confidence, which is far harder to notice.
 *
 * The fixtures are real MediaPipe landmarks with the features Python produced
 * for them, generated by running the actual training-time code path
 * (`LandmarkNormalizer(FULL)` then `LandmarkFeatureExtractor`).
 */
type Case = { raw: number[][]; expected: number[] };
const fixtures = cases as Case[];

const toLandmarks = (raw: number[][]) =>
  raw.map(([x, y, z]) => ({ x, y, z }));

describe("feature parity with the Python training pipeline", () => {
  it("has fixtures to check against", () => {
    expect(fixtures.length).toBeGreaterThan(0);
    expect(fixtures[0].expected).toHaveLength(86);
  });

  it.each(fixtures.map((c, i) => [i, c] as const))(
    "matches Python for sample %i",
    (_i, c) => {
      const actual = extractFeaturesForTest(
        normalizeLandmarks(toLandmarks(c.raw))
      );
      expect(actual).toHaveLength(c.expected.length);
      for (let d = 0; d < c.expected.length; d++) {
        // float32 either side; 1e-5 is far tighter than any difference that
        // could shift a prediction.
        expect(actual[d]).toBeCloseTo(c.expected[d], 5);
      }
    }
  );

  it("produces wildly different features without normalization", () => {
    // Guards the regression directly: extracting from raw landmarks is what
    // the browser used to do, and it must not silently look acceptable.
    const c = fixtures[0];
    const unnormalized = extractFeaturesForTest(toLandmarks(c.raw));
    let maxDelta = 0;
    for (let d = 0; d < c.expected.length; d++) {
      maxDelta = Math.max(maxDelta, Math.abs(unnormalized[d] - c.expected[d]));
    }
    expect(maxDelta).toBeGreaterThan(0.1);
  });
});
